spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wearekhmer
    username: postgres
    password: 1

    #config files
  servlet:
    multipart:
      enabled: true
      file-size-threshold: "2KB"
      max-request-size: 250MB
      max-file-size: 250MB

  mail:
    username: raksmeykoung@gmail.com
    password: qxsayvuxoekwvixo
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
        socketFactory:
          port: 25
          class: javax.net.ssl.SSLSocketFactory
          fallback: true
        transport:
          protocol=smtp:
          auth: true
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: true




user:
  personal:
    repo:
      link: https://github.com/MaheshIare?tab=repositories
      type: Github repo

thymeleaf:
  templates:
    location: classpath:/templates/
    extension: .html
